rssviewer/config/routes.rb
Rails.application.routes.draw do
  get "rss_sources/index"
  get "rss_sources/delete"
  get "rss_sources/create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root :to => 'home#index'

  get "/rss_sources", to: "rss_sources#index"
  get "/rss_sources/new", to: "rss_sources#new"
  get "/rss_sources/:id", to: "rss_sources#show", as: 'rss_source'
  post "/rss_sources", to: "rss_sources#create"
  put "/rss_sources/:id", to: "rss_sources#update"
  delete "/rss_sources/:id", to: "rss_sources#destroy"

end

rssviewer/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rssviewer/app/models/rss_item.rb
class RssItem < ApplicationRecord
end

rssviewer/app/models/rss_source.rb
class RssSource < ApplicationRecord
end

rssviewer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

rssviewer/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    item = RssItem
    item = item.where("title like ?", "%"+params[:title] + "%") unless params[:title].blank?
    item = item.where("source like ?", "%"+params[:source]+"%") unless params[:source].blank?

    @data = item.order("publish_date desc")
  end
end

rssviewer/app/controllers/rss_sources_controller.rb
class RssSourcesController < ApplicationController
  def index
    @data = RssSource.all
  end

  def create
    source = RssSource.new
    source.url = params['rss_source']['url']
    if source.save
      RssJob.perform_later
      redirect_to rss_sources_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @source = RssSource.find(params[:id])
    if @source.delete
      RssJob.perform_later
      redirect_to rss_sources_path
    end
  end

  def new
    @source = RssSource.new 
  end

  def show
    @source = RssSource.find(params[:id])
  end
end

rssviewer/app/helpers/addresses_helper.rb
module AddressesHelper
end

rssviewer/app/helpers/application_helper.rb
module ApplicationHelper
end

rssviewer/app/helpers/home_helper.rb
module HomeHelper
end

rssviewer/app/helpers/rss_sources_helper.rb
module RssSourcesHelper
end

rssviewer/app/helpers/sources_helper.rb
module SourcesHelper
end

rssviewer/app/views/home/index.html.erb
<%= form_with method: :get do |form| %>
<div class="container">
<div class="row">
<div class="col-2">
  <%= form.search_field :title, placeholder: "Title" %>
</div>
<div class="col-2">
  <%= form.search_field :source, placeholder: "Source"   %>
</div>
<div class="col-2">
  <%= form.submit "Search"  %>
</div>
<% end %>
</div>
</div>
<div class="container" id="data">
  <div class="row card-header">
  <div class="col-1 my-0 font-weight-normal">ID</div>
  <div class="col-10">Title</div>
  </div>
  <% @data.each do |item| %>
  <div class="row card-title" id="data">
    <div  class="col-1">
      <%= item.id %>
    </div>
    <div  class="col-10">
      <%= link_to item.title, item.link, :target => "_blank" %>
    </div>
  </div>
<% end %>
</div>

</div>

rssviewer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rssviewer" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div class="container">
    <h1>RSS Viewer</h1>
      <div class="row">
          <div class="col-1"><%= link_to "Home", root_path %> </div>
          <div class="col-1"><%= link_to "Sources", rss_sources_path %></div>
      </div>
    <div class="row mt-2">
    <%= yield %>
  </body>
</html>

rssviewer/app/views/rss_sources/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-1" >RSS Sources</div>
    <div><%= link_to "Add", rss_sources_new_path %></div>
  </div>
</div>
<div class="container">
  <% @data.each do |source| %>
  <div class="row" id="source">
    <div class="col-1"><%= source.id %></div>
    <div class="col-1"><%= link_to "Edit", source %></div>
    <div class="col"><%= source.url %></div>
  </div>
  <% end %>
</div>

rssviewer/app/views/rss_sources/new.html.erb
<div class="container">
  <div class="row">
    <div class="col"><h2>Add source</h2></div>
</div>
<div class="row">
<%= form_with model: @source do |form| %>
  <div class="row">
    <div class="col-md-2 mb-4"><%= form.label :url, "URL", class: "form-control"%></div>
    <div class="col-md-4 mb-4"><%= form.text_field :url, class: "form-control" %></div>
    <div class="col-6"><%= form.submit class: "form-control" %></div>
  </div>
<% end %>
</div>

rssviewer/app/views/rss_sources/show.html.erb
<div class="container">
<div class="row">
</div>
<div class="row">
    <div class="col-1"><%= link_to "Back", rss_sources_path %></div>
    <div class="col-1"><%= button_to "Delete", @source, method: :delete, data: { turbo_confirm: "Are you sure?" } %></div>
    <div class="col-2"><%= @source.url %></div>
</div>
</div>